apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata: 
  name: jlink-builder-jdk-11
  labels:
    app: jlink-builder-jdk-11
spec:
  source:
    dockerfile: |
      FROM -
      USER 0
      RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y java-11-openjdk-jmods
      USER 185
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: ubi9-openjdk-11-jlink:latest

